### ISSUE TITLE
Flesh out Zenoh key conversion tests and align with `up-client-zenoh-cpp`

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-zenoh-rust#23]
Hey @evshary -- could you take a look at the tests [in this commit](https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/pull/23/commits/5bbb6dd36ba1591ea5b5f731093ff0c962c95f88) and see if we can align the tests here? @gregmedd realized we should have IPv4 and IPv6 tests.

Generally speaking the cpp and rust Zenoh clients need to interoperate so I think it'd be great if we aligned :+1:

**Comment by evshary** [comment]
I think the test coverage is more complete in #40 now.
