### ISSUE TITLE
Update to up-rust 1.5.8 release tag

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-zenoh-rust#53]
Hey @evshary :wave: 

Opening this issue here similar to the [one I opened](https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust/issues/6) over on up-transport-vsomeip-rust

I'd like to keep in sync, so kinda putting this as a reminder to stay in sync :slightly_smiling_face:

**Comment by evshary** [comment]
Yes, I also plan to update up-transport-zenoh-rust to catch up with up-rust recently. Thanks for raising this.
BTW, do we have `up-rust` release tag already? I didn't see it on the repo.

**Comment by stevenhartley** [comment]
I know @sophokles73 was talking about making one very soon....

**Comment by evshary** [comment]
Thank you for the information. Then we can also plan how to release the packages to `crates.io` afterward. It will be convenient for users to download the library directly.
