### ISSUE TITLE
Cutting a release tag + submission to crates.io

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-zenoh-rust#62]
Hi @evshary --

I'm looking to be able to depend on a more stable release over in up-streamer-rust.

Could you cut a release tag?

Might be good to also release onto crates.io if you feel it's stable enough for a 0.10 release.

**Comment by evshary** [comment]
Yes, it's on my TODO list. I just finished some async migration in Zenoh (Use tokio instead of async_std in plugins). Hopefully, the release will be done soon.

**Comment by evshary** [comment]
@PLeVasseur Now the v0.1.0 is released
https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/releases/tag/v0.1.0
You can also access it from crates.io
https://crates.io/crates/up-transport-zenoh
