### ISSUE TITLE
Support informing why the uri cannot be converted to a UUri

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-zenoh-rust#77]
In [this code snippet](https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/blob/3993807a84d372de81f24c6b6f6ef936d45acce0/src/lib.rs#L143) we drop the error that came through in the map_err.

We should probably keep it so that a user knows that went wrong and how to fix it.

**Comment by evshary** [comment]
Should be fixed in https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/84
