### ISSUE TITLE
Consider supporting associated `new` functions which take a `UUri` struct

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-transport-zenoh-rust#78]
May just be me :sweat_smile: but I like using the `UUri::try_from_parts()` function from `up-rust` for creating `UUri`s.

To initialize a `UPTransportZenoh` I currently have to do that, then convert from the `UUri` back to a `String` or `&str`.

Can we consider supporting associated `new` functions which take a `UUri` struct to avoid that little dance?

**Comment by evshary** [comment]
Fixed in https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/84
