### ISSUE TITLE
Use pub/sub only of Zenoh (not queriables)

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-transport-zenoh-rust#79]
Per https://github.com/eclipse-uprotocol/up-spec/discussions/229, switch transport implementations of zenoh to use pub/sub only even for RPC and notification type of events. This is to drastically simplify the transport implementions

**Comment by stevenhartley** [comment]
Related to the C++ issue https://github.com/eclipse-uprotocol/up-transport-zenoh-cpp/issues/109

**Comment by evshary** [comment]
Done via https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/83
