### ISSUE TITLE
The failure of nightly build

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-transport-zenoh-rust#86]
For example, we always fail when building on different platforms.
https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/actions/runs/11379141927/job/31656065596
It's weird that it will succeed if we don't use `Swatinem/rust-cache@v2`
https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/blob/f13821a314ff25876a58fd52e9c204248fc6218f/.github/workflows/x-build.yaml#L58

@sophokles73 Have you faced this kind of issue before?

**Comment by sophokles73** [comment]
No, I haven't. But it seems that your [test_nightly](https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/compare/main...test_nightly) branch actually succeeds, right?

**Comment by evshary** [comment]
> No, I haven't. But it seems that your [test_nightly](https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/compare/main...test_nightly) branch actually succeeds, right?

Yes, it works either I have `cargo clean` or remove `Swatinem/rust-cache@v2`...

**Comment by evshary** [comment]
Might be related. Will give it a try
https://github.com/eclipse-zenoh/zenoh/pull/1542

**Comment by evshary** [comment]
Hmm.... after updating Zenoh, the issue disappeared. Not sure what happened.

**Comment by evshary** [comment]
Since Zenoh has been updated to the latest version, let's close the issue for now.
https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/actions/runs/11512988311
