### ISSUE TITLE
Bumping up-transport-zenoh-rust version

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-transport-zenoh-rust#88]
Since now Zenoh 1.0.0 has been officially released and we are upgrading up-transport-zenoh-rust, it might be a good chance to bump the version.
@sophokles73 We discussed the version policy before, but I forgot the conclusion. Do we need to keep the same minor version across all the projects? For example, `up-rust` is 0.2.x, and `up-transport-xxx-rust` will also be fixed at 0.2.y.

**Comment by sophokles73** [comment]
No, each component may freely follow its own versioning. However, we must follow semantic versioning. While we are still at major version 0, this doesn't mean much, i.e. you can break the API between minor versions etc. 
IIRC up-transport-zenoh uses Zenoh type in its public API for creating a transport instance. If that is true, then IMHO bumping the Zenoh dependency to 1.0.0 should be reflected in a minor version increase of up-transport-zenoh as well. WDYT?

**Comment by evshary** [comment]
Sounds good to me.
